[package]
name = "wayrs-scanner"
description = "Generates code for wayrs-client from xml files"
repository = "https://github.com/MaxVerevkin/wayrs"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["MaxVerevkin <maxxverrr@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
quick-xml = "0.26"
quote = "1.0"
proc-macro2 = "1.0.47"
convert_case = "0.6.0"

[dependencies.syn]
version = "1.0"
default-features = false
features = ["parsing", "proc-macro"]
