[package]
name = "wayrs-scanner"
description = "Generates code for wayrs-client from xml files"
repository = "https://github.com/MaxVerevkin/wayrs"
readme = "../README.md"
version = "0.7.0"
edition = "2021"
license = "MIT"
authors = ["MaxVerevkin <maxxverrr@gmail.com>"]
keywords = ["wayland", "client", "scanner"]

[lib]
proc-macro = true

[dependencies]
quick-xml = "0.28"
quote = "1.0"
proc-macro2 = "1.0"
convert_case = "0.6"

[dependencies.syn]
version = "2.0"
default-features = false
features = ["parsing", "proc-macro"]
