[package]
name = "wayrs-client"
description = "A simple wayland library"
repository = "https://github.com/MaxVerevkin/wayrs"
readme = "../README.md"
version = "0.2.1"
edition = "2021"
license = "MIT"
authors = ["MaxVerevkin <maxxverrr@gmail.com>"]
keywords = ["wayland", "client"]

[dependencies]
wayrs-scanner = { version = "0.2.0", path = "../wayrs-scanner" }
thiserror = "1.0"

[dependencies.nix]
version = "0.26"
default-features = false
features = ["socket", "uio"]

[dependencies.tokio]
version = "1"
optional = true
default-features = false
features = ["net"]
