on: [push, pull_request]

name: Rust

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Get required packages
        run: sudo apt-get update && sudo apt-get install libxkbcommon-dev
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@1.60.0
      - name: Check
        run: cargo check --all --all-features

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Get required packages
        run: sudo apt-get update && sudo apt-get install libxkbcommon-dev
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@1.60.0
      - name: Tests
        run: cargo test --all --all-features

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Get required packages
        run: sudo apt-get update && sudo apt-get install libxkbcommon-dev
      - name: Get required packages
        run: sudo apt-get install fd-find
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@1.60.0
      - name: Fmt check
        run: rustfmt --check --edition 2021 $(fdfind -e rs)

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Get required packages
        run: sudo apt-get update && sudo apt-get install libxkbcommon-dev
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@1.60.0
      - uses: actions-rs/cargo@v1
      - name: Clippy check
        run: cargo clippy --all --all-features -- -D warnings -A unknown-lints
